# Site settings
title: Queer Collaborations 2015
email: qcanu2015@gmail.com
description: "Queer Collaborations is an annual gathering of queer students from around Australia.  In 2015, it is being held at the Australian National University."
baseurl: ""
url: "http://qcanu2015.com"

# Build settings
markdown: kramdown
permalink: pretty
